# Generated by Django 4.0.5 on 2022-07-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=800)),
                ('fecha_viaje', models.DateField()),
            ],
        ),
    ]
