# Generated by Django 4.0.5 on 2022-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0002_publicaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='publicaciones',
            table='imageupload',
        ),
    ]
