# Generated by Django 4.0.5 on 2022-07-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0004_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
