# Generated by Django 4.0.5 on 2022-07-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0005_alter_publicaciones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
