# Generated by Django 4.0.5 on 2022-07-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0006_alter_publicaciones_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
