# Generated by Django 4.0.5 on 2022-07-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0009_alter_publicaciones_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='usuario',
        ),
    ]
